version: '3.7'

volumes:
  couchdb.org1:
  couchdb.org2:
  couchdb.org3:

networks:
  fabric_network:
    name: fabric_network
    external: true

services:
  couchdb.org1:
    container_name: couchdb.org1
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"
    volumes:
      - couchdb.org1:/opt/couchdb/data
    networks:
      - fabric_network

  couchdb.org2:
    container_name: couchdb.org2
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "8984:5984"
    volumes:
      - couchdb.org2:/opt/couchdb/data
    networks:
      - fabric_network

  couchdb.org3:
    container_name: couchdb.org3
    image: couchdb:3.3.2
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9984:5984"
    volumes:
      - couchdb.org3:/opt/couchdb/data
    networks:
      - fabric_network
